# Generated by Django 4.0 on 2023-07-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.TextField()),
                ('title', models.TextField()),
                ('category', models.IntegerField(choices=[(1, 'Appetizers'), (2, 'Mains'), (3, 'Sauces'), (4, 'Desserts'), (5, 'Drinks')])),
                ('description', models.TextField(blank=True)),
                ('serves', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cooktime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ingredients', models.JSONField()),
                ('ingredient_parts', models.JSONField()),
                ('steps', models.TextField()),
                ('notes', models.TextField()),
                ('labels', models.ManyToManyField(to='core.Label')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_slug'),
        ),
    ]
